language: python

python:
  - "2.7"

# commands to install dependencies
before_install:
  - pip install codecov

install:
  - pip install .
  - pip install coverage
# command to run tests
script: coverage-2.7 run setup.py test

after_success:
  - codecov
