language: python
python:
  - "2.7"
# command to install dependencies
install:
  - "pip install ."
  - "pip install coveralls"
  - "pip install coverage"
# command to run tests
script: coverage run setup.py test

after_success:
    coveralls
