name: CI
runs-on: self-hosted

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: echo $GITHUB_SHA && echo $GITHUB_REF
